### ISSUE TITLE
OSGeo4W not required?

### ISSUE THREAD

**Issue by jsta** [jannes-m/RQGIS#11]
The `README.md` suggests that an `OSGeo4W` folder + installation is necessary. I am on Windows and I do not have such an installation. I was able to run the `README.md` tutorial just fine by setting:

> `my_env <- set_env("C:/Program Files/QGIS Wien")`

Is an `OSGeo4W` folder + installation strictly necessary? If not, I think the `check_apps` error message:
> `Please install qgis using the 'OSGEO4W' advanced installation routine.` 

would be more informative if it was changed to something like:

> `No qgis installation found at the specified path.`

**Comment by jannes-m** [comment]
Hello,

thanks for this remark. You are right, you can install the standalone version of QGIS and still are able to run RQGIS. Still we would recommend to use the OSGeo4w version since this ensures that all dependencies are installed correctly. Nevertheless, you are absolutely right, that I should change the error message to something a bit more informative (already done).

All the best,

Jannes
