### ISSUE TITLE
Problem with assigning via run_qgis directly

### ISSUE THREAD

**Issue by karstenv** [jannes-m/RQGIS#47]
I created an example on creating contours from a DEM raster (on windows) . This works see - see the R script below and screenshot. However I had to use readOGR  (see line 54 in text file below)  to assign the output contour shape file. This seems to be a bug to me (as it worked directly to another algorithm such as buffer e.g.). Can this be fixed ?

![tz_200m_contours](https://cloud.githubusercontent.com/assets/1751260/22714988/dbe243b2-ed43-11e6-992f-c815ea0ecde9.png)
[rqgis_contours_tz.txt](https://github.com/jannes-m/RQGIS/files/759247/rqgis_contours_tz.txt)

**Comment by pat-s** [comment]
@karstenv thanks for reporting your issue! 

A few notes first: 

- Please avoid inserting screenshots of your RStudio IDE if that does not add any value (the plot would have been sufficient but also not essential)
- Also it is more efficient to shrink down the code to lines which cause the error instead of providing your whole script. This simplifies the understanding of your issue.

Regarding your issue: You need to use `load_output = con_params$OUTPUT_VECTOR` instead of `load_output = con_params$OUTPUT_LAYER` in `run_qgis`. Double-check the function arguments of `gdalogr::contour` as returned by `get_args_man()`.

See a full reproducible example here:

```r
pacman::p_load(RQGIS, raster)

my_env <- set_env()
data("dem")

con_params <- get_args_man(alg = "gdalogr:contour", 
                           qgis_env = my_env)

con_params$OUTPUT_VECTOR <- file.path(tempdir(), "tz_contours1.shp")
con_params$INPUT_RASTER  <- dem
con_params$INTERVAL <- "\"200\""
con_params$FIELD_NAME <- "\"m\""

tz_200m_contours <- run_qgis(alg = "gdalogr:contour",
                             params = con_params,
                             load_output = con_params$OUTPUT_VECTOR,
                             qgis_env = my_env)

plot(dem)
plot(tz_200m_contours, add = TRUE, col = "darkred" )
```

![rplot](https://cloud.githubusercontent.com/assets/8430564/22716404/3b014a12-ed96-11e6-8c83-625b85119cef.png)

**Comment by karstenv** [comment]
Hi Jannes,
 
thanks for your notes to help me improve filing issues. 
 
 >>>  Regarding your issue: You need to use load_output =
con_params$OUTPUT_VECTOR instead of load_output = con_params$OUTPUT_LAYER in
run_qgis. Double-check the function arguments of gdalogr::contour as
returned by get_args_man(). 
Ah I see now.
I did not realize at all that I had missed to replace the parameter (from a
script which I used before with another procedure gdalogr:buffervectors )  
params$OUTPUT_LAYER with params$OUTPUT_VECTOR . It works all now.

Thanks so much and thanks for creating RQGIS in general really cool to have
that !
 
Cheers
Karsten
 
www.terragis.net
