### ISSUE TITLE
Replace py_cmd and build_cmd with reticulate

### ISSUE THREAD

**Issue by pat-s** [jannes-m/RQGIS#59]
* Leave old approach as backup for Windows when installed Python/Numpy is not sufficient for `reticulate`. Also, if someone has a running `reticulate` session we cannot overwrite the reticulate config -> R restarted needed. In this case, use the fall back option if the running `reticulate` config is not sufficient for QGIS
* No problems for Linux/Mac because we are using `/usr/bin/python` which should work in any case

**Comment by jannes-m** [comment]
We have completely rewritten RQGIS using `reticulate` (df39990). We opted for deleting the old way of accessing the QGIS API due to (a probably unnecessary) increased package complexity when supporting several ways of implementing the same behavior. However, if necessary, we can re-implement the old implementation.
