### ISSUE TITLE
Using sf objects

### ISSUE THREAD

**Issue by SFrav** [jannes-m/RQGIS#66]
In the future will it be possible to use Simple Features objects? At the moment I'm using RQGIS v 0.2.0.

https://cran.r-project.org/web/packages/sf/sf.pdf

**Comment by jannes-m** [comment]
Thanks to @eivindhammers RQGIS already supports simple features. Check out https://github.com/jannes-m/RQGIS/tree/dev for more information. However, we wait with the integration until the next `sf`-release on CRAN due to an issue while overwriting files with `st_write` (see https://github.com/edzer/sfr/issues/307).

**Comment by Robinlovelace** [comment]
This is fantastic news - and definitely makes me want to cover RQGIS in our upcoming [book](https://github.com/Robinlovelace/geocompr).

Heads-up: I may have questions for you - will try to install on Ubuntu 16.04 to give it a spin.

cc @nowosad I think this will be really useful to include, not sure where though.

**Comment by Nowosad** [comment]
@Robinlovelace I've added this to our list (https://github.com/Robinlovelace/geocompr/issues/12) last week;)

**Comment by pat-s** [comment]
@Robinlovelace @Nowosad maybe we will find some time to contribute ;)

**Comment by jannes-m** [comment]
@Robinlovelace @Nowosad I came across your new book just a week ago. To be honest, I always wanted to write a book like this. In fact, two years ago I started to write the first chapter but then... So please let me know if I can be of any help, I would love to contribute! 
Since you call your book geocomputation with R, I think a chapter on R/GIS integration is a prerequisite, simply because R was never designed as a GIS, and therefore is missing much of the functionality of a GIS. Secondly, R is not that good at processing large amounts of spatial data. You could implement that in R (using C++ etc.) but why reproduce already available GIS functionality if we can access it via an interface. By the way, stuff like this we are discussing in a paper that we would like to submit within the next month. If you are more interested in this, we can share with you the manuscript.

**Comment by Robinlovelace** [comment]
Hi Jannes, I think a section on R/GIS integration deserves its own chapter. Not sure where that would go yet but I think chapter 12 on algorithms could usefully shift to chapter 13, providing space for it.

Regarding opportunities to contribute, we are still at the early stages of this book, there is so much to cover, so there are many opportunities! It's really exciting that things are moving fast in the R/GIS world but the priority should be to get strong foundations, hence our emphasis on solid use of `sf` objects in the opening chapters - any thoughts on that welcome.

Regarding speed, we would welcome more benchmarks in the [I/O chapter](http://robinlovelace.net/geocompr/read-write.html).

+ I think you would be very well-placed to write something on R/GIS integration - I've very happy to provide guidance on that - e.g. here's a starter for 10: https://github.com/Robinlovelace/geocompr/pull/33

**Comment by Nowosad** [comment]
@jannes-m - and it would be great if you could share this manuscript with us.

**Comment by Robinlovelace** [comment]
+1 re manuscript - yes that would be really useful. Any general ideas/comments welcome.

**Comment by jannes-m** [comment]
@Robinlovelace @Nowosad Thank you both for your thoughts! Give me a couple of weeks before sharing our manuscript. At the moment I am rewriting and updating it. Regarding contributing, I would be happy to write something on R/GIS integration, so please provide input! 
At the moment I am a bit busy with teaching, nevertheless I will read your book and have a look at the code that Jakub provided (thanks!) within the next two weeks.

**Comment by Robinlovelace** [comment]
That sounds good to me re timing - no rush on this but I'm increasingly thinking this will be an important component of the book, especially for ppl coming to R from a GIS background.

In terms of input - a good starting point could be just writing down some ideas as they come-up here - in the web-editor is fine.

We can worry about polishing things after the ideas and structure are in there:

https://github.com/Robinlovelace/geocompr/edit/cli-gui-integration/cli-gui-integration.Rmd?pr=/Robinlovelace/geocompr/pull/33
