### ISSUE TITLE
Problems running rqgis(alg="grass7:r.water.outlet")

### ISSUE THREAD

**Issue by ghiggi** [jannes-m/RQGIS#81]
I am trying to run the grass7:r.water.outlet algorithm using rqgis() but I get many different errors when I specify the parameter "coordinates".

Setting up parameters:
`params <- get_args_man(alg = "grass7:r.water.outlet" )# Retrieves function arguments`
`params$input <- flow.raster   # class raster`
`params$GRASS_REGION_PARAMETER <- paste(box[1]-4, box[2]+4, box[4]-4, box[3]+4, sep=",")`
`params$output <- file.path(local_repository, "ID_catch_1.tif"))`
`params`

I tried the following set up for the coordinates:
`coords <- coordinates(sp_point)`
`params$coordinates <- paste0(coords[1],",", coords[2]) # "long,lat" format`
`params$coordinates <- sf_point     # sf object`
`params$coordinates <- sp_point    # SpatialPoint`

-  If I provide a Spatial Point object (single obs.), I get the following error:
    > Error in as.character.default(x) :   no method for coercing this S4 class to a vector"

- If I provide a sf object, rgis() create a correct temporary .shp file in 
   `C:\Users\Ghiggi\AppData\Local\Temp\RtmpXXX`,  but I get the following error from function pass_args() in rqis(): 
    > Error  in pass_args(alg, ..., params = params, qgis_env = qgis_env) : Invalid argument value C:\Users\Ghiggi\AppData\Local\Temp\RtmpaOpi78/coordinates.shp for parameter coordinates

    The error is generated by py_run_string() at line 78 of pass_args() 
 
- When I provide the coordinates in character format "long,lat" with the following code:
` coords <- st_coordinates(sf_point) # or  coord <- coordinates(sp_point)` 
` params$coordinates <- paste0(coords[1],",", coords[2])` 

   rqgis() correctly format the coordinate string (i.e. "\\"8.8919,46.1593\\"") , the computation seems to start, but at the end I obtain:
    > Error in FUN(X[[i]], ...) :  Unfortunately, QGIS did not produce: D:\PATH\ID_catch_1.tif 

As I final remark, when I tried to personalize GRASS_REGION_PARAMETER, I observed that when rqis() try to define it automatically, it almost return the bbox of the raster layer in the following format  "xmin, ymin , **ymax , xmax**" (top left, bottom right). However, when using bbox() (or st_box()) we obtain coordinates in the following order [xmin  ymin  **xmax  ymax**],  rqis() inverts the last two elements ... is this desired or it might be a bug? 

You can find a R script with sample data here:  https://github.com/ghiggi/Temp

Thanks in advance !
--------------------------------------------------------------------------------------------------
`qgis_session_info()`
`$qgis_version`
`[1] "2.18.12"`
`$gdal`
`[1] "2.2.1"`
`$grass6`
`[1] FALSE`
`$grass7`
`[1] "7.2.1"`
`$saga`
`[1] "2.1.2"`
`$supported_saga_versions`
`[1] "2.3.0" "2.3.1"`

**Comment by jannes-m** [comment]
`open_help("grass7:r.water.outlet")` tells you to specify parameter `coordinates` with an x and y coordinate (see example of the help page), so your final approach using `"8.8919,46.1593"` (assuming that 8.8 is x and 46.2 is y) is correct.

However, there is a problem with GRASS here. Running:
```r
library("RQGIS")
data("dem")
run_qgis("grass7:r.watershed", drainage = file.path(tempdir(), "drain.tif", elevation = dem, load_output = TRUE)
```
tells us, that various output rasters have been created (among others a drainage raster, which we would need for the `grass7:r.water.outlet` function), however all the folders are empty. This is hard to debug since QGIS tells us everything went fine. We have encountered this problem various times before, so we need to file a bug report to the QGIS developer core team. This will take a while since I am on vacation until 10.10. So in the meantime I would suggest to have a look if SAGA or GDAL provides a similar functionality. If you want to use GRASS, I would recommend to use `rgrass7`. How to do so, have a look at my [r-gis bridges chapter](https://github.com/Robinlovelace/geocompr/blob/master/13-gis.Rmd).

I also tried your example
```r
 out = run_qgis("grass7:r.water.outlet", input = flow.raster, 
               coordinates = "8.8919,46.1593", load_output = TRUE)
```
This actually creates an output, however, it is a raster consisting only of NAs. Is `flow.raster` a drainage raster as expected by GRASS (see again `open_help("grass7:r.water.outlet")`).

Regarding your second GRASS_REGION_PARAMETER question. If you run:
```r
pass_args("grass7:r.water.outlet", input = flow.raster)
```
the output is:

```r
$input
[1] "C:/Users/pi37pat/AppData/Local/Temp/Rtmp86LKR7/input1111.tif"

$coordinates
[1] "\"\""

$GRASS_REGION_PARAMETER
[1] "-14,69.9999999999986,12,61.9999999999992"

$GRASS_REGION_CELLSIZE_PARAMETER
[1] "0.0"

$output
[1] "None"
```

Hence the GRASS_REGION_PARAMETER corresponds to xmin, xmax, ymin, ymax, exactly like it should be according to the QGIS documentation. See also `extent(flow.raster)`.

**Comment by pat-s** [comment]
@ghiggi Problem solved? Feel free to re-open if needed.

**Comment by jannes-m** [comment]
`grass7:r.water.outlet` still produces not output despite QGIS telling us otherwise (I mean QGIS come up with output paths, however, the corresponding folders are empty).

**Comment by ghiggi** [comment]
Sorry for the late answer. 
I finally implemented the algorithm by myself in R. D8 catchment delineation can be easily done solving a linear system of equation using sparse matrix algebra.  The code is also lot faster than the one executed in QGIS.  If interested, I can send you the code. I also found that the largest issue in delineating the catchment is to find the correct "accumulation point" from which to delineate the catchment.

**Comment by jannes-m** [comment]
Great, that you could solve your problem programmatically! Sorry, I didn't catch that you merely wanted to compute a D8 catchment area. SAGA provides also a few algorithms doing that, and is usually faster than GRASS when it comes to raster processing. If still interested, have a look at `get_usage("saga:flowwidthandspecificcatchmentarea")`.
